name: "Hello World"
description: "Greet someone and record the time"
inputs:
  json-file-path: # id of input
    description: "data.json"
    required: true
    default: "data.json"
outputs:
  time: # id of output
    description: "The time we greeted you"
runs:
  using: "node12"
  main: "index.js"
