name: "Hello World"
on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v2
      - name: Hello world action step
        id: hello
        uses: muchirijane/github-action-readme-profiles@master
        with:
          json-file-path: "data.json"
          github-token: ${{secrets.GITHUB_TOKEN}}
